/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-display)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
        utility: ['var(--font-utility)', 'monospace'],
      },
      fontSize: {
        'display-xl': 'var(--font-size-display-xl)',
        'display-lg': 'var(--font-size-display-lg)',
        'display-md': 'var(--font-size-display-md)',
        'display-sm': 'var(--font-size-display-sm)',
        'body-lg': 'var(--font-size-body-lg)',
        'body-md': 'var(--font-size-body-md)',
        'body-sm': 'var(--font-size-body-sm)',
        'body-xs': 'var(--font-size-body-xs)',
        'caption-md': 'var(--font-size-caption-md)',
        'caption-sm': 'var(--font-size-caption-sm)',
      },
      lineHeight: {
        'tight': 'var(--line-height-tight)',
        'normal': 'var(--line-height-normal)',
        'relaxed': 'var(--line-height-relaxed)',
        'loose': 'var(--line-height-loose)',
      },
      letterSpacing: {
        'tight': 'var(--letter-spacing-tight)',
        'normal': 'var(--letter-spacing-normal)',
        'relaxed': 'var(--letter-spacing-relaxed)',
        'wide': 'var(--letter-spacing-wide)',
      },
      spacing: {
        'xs': 'var(--spacing-xs)',
        'sm': 'var(--spacing-sm)',
        'md': 'var(--spacing-md)',
        'lg': 'var(--spacing-lg)',
        'xl': 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
        '4xl': 'var(--spacing-4xl)',
        '5xl': 'var(--spacing-5xl)',
        'content-xs': 'var(--spacing-content-xs)',
        'content-sm': 'var(--spacing-content-sm)',
        'content-md': 'var(--spacing-content-md)',
        'content-lg': 'var(--spacing-content-lg)',
        'content-xl': 'var(--spacing-content-xl)',
        'component-xs': 'var(--spacing-component-xs)',
        'component-sm': 'var(--spacing-component-sm)',
        'component-md': 'var(--spacing-component-md)',
        'component-lg': 'var(--spacing-component-lg)',
        'component-xl': 'var(--spacing-component-xl)',
        'layout-xs': 'var(--spacing-layout-xs)',
        'layout-sm': 'var(--spacing-layout-sm)',
        'layout-md': 'var(--spacing-layout-md)',
        'layout-lg': 'var(--spacing-layout-lg)',
        'layout-xl': 'var(--spacing-layout-xl)',
        'layout-2xl': 'var(--spacing-layout-2xl)',
      },
      minWidth: {
        'touch': 'var(--touch-target-minimum)',
        'touch-lg': 'var(--touch-target-recommended)',
        'touch-xl': 'var(--touch-target-large)',
      },
      minHeight: {
        'touch': 'var(--touch-target-minimum)',
        'touch-lg': 'var(--touch-target-recommended)',
        'touch-xl': 'var(--touch-target-large)',
      },
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
        },
        background: {
          DEFAULT: 'var(--color-background)',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
        },
        text: {
          DEFAULT: 'var(--color-text)',
          secondary: 'var(--color-textSecondary)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
        },
        error: {
          DEFAULT: 'var(--color-error)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
        },
      },
    },
  },
  plugins: [],
}
